# Generated by Django 3.2 on 2021-04-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
