# Generated by Django 3.2 on 2021-04-30 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month', '0002_alter_month_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
